FROM golang:1.13-alpine3.10 AS builder
WORKDIR /go/src 
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn
ADD consumer.go .
RUN apk add --no-cache gcc
RUN go build -o /go/bin/consumer consumer.go

FROM alpine:3.10
COPY --from=builder /go/bin/consumer /app/
CMD ["/app/consumer"]