apiVersion: v1
kind: Secret
metadata:
  name: pulsar-consumer
data:
  pulsarHost: YW1xcDovL3VzZXI6UEFTU1dPUkRAcmFiYml0bXEuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-consumer
  namespace: default
  labels:
    app: pulsar-consumer
spec:
  selector:
    matchLabels:
      app: pulsar-consumer
  template:
    metadata:
      labels:
        app: pulsar-consumer
    spec:
      containers:
      - name: pulsar-consumer
        image: lanpulsar/consumer:0.2
        imagePullPolicy: IfNotPresent
        env:
          - name: pulsarHost
            value: pulsar://192.168.1.89:30552
          - name: topic
            value: persistent://public/default/demo3
          - name: subscriptionName
            value: demokeda
        envFrom:
        - secretRef:
            name: pulsar-consumer
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: pulsar-consumer
  namespace: default
  labels:
    deploymentName: pulsar-consumer
spec:
  scaleTargetRef:
    deploymentName: pulsar-consumer
  pollingInterval: 5   # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds
  maxReplicaCount: 30  # Optional. Default: 100
  triggers:
  - type: pulsarmq
    metadata:
      topicName: persistent://public/default/demo3
      adminHost: http://192.168.1.89:30641/admin/v2/persistent/public/default/demo3/stats
      subscriptionName: demokeda
      backlogLen: '30'
      
---
